export const BASE_URL = 'http://localhost:8800' 
export const GET_CATEGORIES  = '/api/category/'
export const GET_PRODUCTS  = '/api/products/'
export const GET_BRANDS  = '/api/brands/'
export const GET_PRODUCTS_FOR_CATEGORY = '/api/products/'
export const GET_ATTRIBUTES_BY_CATEGORY = '/api/attribute/'
export const UPLOAD_PRODUCT_IMAGE = 'api/products/upload'
export const SAVE_PRODUCT = '/api/products'
export const PATCH_PRODUCT_IMAGE = '/api/products/'
export const PATCH_PRODUCT_REQUEST_IMAGE = '/api/products/request'
export const GET_MODELS = '/api/models/'
export const GET_RAM_STORAGE_CONFIG = '/api/phoneconfig'
export const APPROVE_PRODUCT_REQUEST = '/api/admin/products/approve'
export const REJECT_PRODUCT_REQUEST = '/api/admin/products/reject'
export const GENERATE_ADHAR_OTP = '/api/otp/generate'
export const VERIFY_ADHAR_OTP = '/api/otp/verify'
export const REGISTER = '/api/signup'
export const SAVE_PRODUCT_REQUEST = '/api/products/request'
export const ADD_TO_CART = '/api/cart'
export const GET_FROM_CART = '/api/cart'
export const UPDATE_CART_QTY = '/api/cart'
export const GET_REQUESTS = '/api/requests'


